import { test, before, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpDir, makeStubBin } from './helpers.ts';

let home: string;
let db: typeof import('../src/db.ts');
let digestMod: typeof import('../src/digest.ts');
const origLog = console.log;

before(async () => {
  home = tmpDir();
  process.env.RUDDER_HOME = home;
  db = await import('../src/db.ts');
  digestMod = await import('../src/digest.ts');
});

after(() => {
  rmSync(home, { recursive: true, force: true });
  console.log = origLog;
});

beforeEach(() => {
  db.openDb().exec('DELETE FROM prompts;');
  console.log = () => {}; // silence digest's progress logging
});

/** Seed one prompt for today and return today's day key. */
function seedToday(): string {
  db.insertPrompt({ source: 'claude', prompt: 'Do a thing', cwd: '/repos/x', project: 'x' });
  return db.localDay();
}

test('digest throws when there are no prompts for the day', () => {
  assert.throws(() => digestMod.digest({ day: '1999-01-01' }), /No prompts recorded for 1999-01-01/);
});

test('digest resolves the default agent, runs it, and writes the digest file', () => {
  const day = seedToday();
  const bin = tmpDir('rudder-bin-');
  makeStubBin(bin, 'claude', { out: 'DIGEST BODY' });
  const out = join(tmpDir('rudder-out-'), 'digest.md');

  const written = withPathSync(bin, () => digestMod.digest({ day, out }));

  assert.equal(written, out, 'digest returns the resolved output path');
  const content = readFileSync(out, 'utf8');
  assert.ok(content.startsWith(`# Work Digest — ${day}`));
  assert.ok(content.includes('Generated by rudder from 1 prompts'));
  assert.ok(content.includes('DIGEST BODY'));
  assert.ok(content.endsWith('\n'));
});

test('digest honors an explicit --agent codex', () => {
  const day = seedToday();
  const bin = tmpDir('rudder-bin-');
  makeStubBin(bin, 'codex', { out: 'CODEX SUMMARY' });
  const out = join(tmpDir('rudder-out-'), 'digest.md');

  withPathSync(bin, () => digestMod.digest({ day, agent: 'codex', out }));
  assert.ok(readFileSync(out, 'utf8').includes('CODEX SUMMARY'));
});

test('digest throws when neither claude nor codex is on PATH', () => {
  const day = seedToday();
  const emptyBin = tmpDir('rudder-empty-');
  assert.throws(
    () => withPathSync(emptyBin, () => digestMod.digest({ day, out: join(emptyBin, 'd.md') })),
    /Neither `claude` nor `codex` was found on your PATH/
  );
});

test('digest surfaces ENOENT for an explicitly chosen but missing agent', () => {
  const day = seedToday();
  const emptyBin = tmpDir('rudder-empty-');
  assert.throws(
    () =>
      withPathSync(emptyBin, () =>
        digestMod.digest({ day, agent: 'claude', out: join(emptyBin, 'd.md') })
      ),
    /'claude' was not found on your PATH/
  );
});

test('digest surfaces a non-zero agent exit with its stderr', () => {
  const day = seedToday();
  const bin = tmpDir('rudder-bin-');
  makeStubBin(bin, 'claude', { exit: 3, out: '', err: 'kaboom' });
  assert.throws(
    () => withPathSync(bin, () => digestMod.digest({ day, agent: 'claude', out: join(bin, 'd.md') })),
    /exited with code 3[\s\S]*kaboom/
  );
});

// digest() is synchronous, so run it with PATH set/restored inline.
function withPathSync<T>(dir: string, fn: () => T): T {
  const orig = process.env.PATH;
  process.env.PATH = dir;
  try {
    return fn();
  } finally {
    if (orig === undefined) delete process.env.PATH;
    else process.env.PATH = orig;
  }
}
