import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { promptsForDay, localDay, type PromptRow } from './db.ts';

export type Agent = 'claude' | 'codex';

export interface DigestOptions {
  day?: string;
  agent?: Agent;
  out?: string;
}

function renderPrompts(rows: PromptRow[]): string {
  const byProject = new Map<string, PromptRow[]>();
  for (const r of rows) {
    const key = r.project || '(unknown)';
    (byProject.get(key) ?? byProject.set(key, []).get(key)!).push(r);
  }

  const blocks: string[] = [];
  for (const [project, list] of byProject) {
    const lines = list.map((r) => {
      const time = new Date(r.ts).toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
      });
      const text = r.prompt.replace(/\s+/g, ' ').trim();
      return `- [${time}] (${r.source}) ${text}`;
    });
    blocks.push(`## Project: ${project} (${list.length} prompts)\n${lines.join('\n')}`);
  }
  return blocks.join('\n\n');
}

function buildInstruction(day: string, rendered: string): string {
  return `You are writing a concise end-of-day work digest for a software engineer, based on the prompts they gave their AI coding assistants (Claude Code and Codex) on ${day}.

Below is the chronological list of every prompt they sent, grouped by project. Use it to infer what they actually worked on. Prompts are noisy and overlapping — synthesize, do not just restate them.

Produce a Markdown digest with these sections:
1. A one-paragraph **Summary** of the day at a high level.
2. **Highlights** — notable accomplishments, hard problems, or decisions, if any are evident. This section should be in line with the next three.
3. **Architecting** — designing new systems, structure, APIs, or overall approach. State the percentage of the day's prompts that fall into this category, followed by up to the top 3 things they worked on.
4. **Tuning** — refining, optimizing, configuring, or adjusting existing behavior. State the percentage of the day's prompts that fall into this category, followed by up to the top 3 things they worked on.
5. **Bugfixing** — diagnosing and fixing defects, errors, or failing tests. State the percentage of the day's prompts that fall into this category, followed by up to the top 3 things they worked on.
6. **Open threads** — anything that looks unfinished or like a next step.

For Architecting, Tuning, and Bugfixing, classify each prompt into at most one of the three categories; prompts that fit none are simply left out of those percentages (so the three percentages need not sum to 100%). Be specific and grounded in the prompts. Do not invent work that isn't supported by the data. Output ONLY the Markdown digest, with no preamble.

---
PROMPTS FOR ${day}:

${rendered}`;
}

function runAgent(agent: Agent, instruction: string): string {
  const cmd =
    agent === 'claude'
      ? { bin: 'claude', args: ['-p'] }
      : { bin: 'codex', args: ['exec', '-'] };

  const res = spawnSync(cmd.bin, cmd.args, {
    input: instruction,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    // Prevent the agent we spawn from re-triggering rudder's own hooks and
    // recording this digest instruction as a prompt for the day.
    env: { ...process.env, RUDDER_DISABLE: '1' },
  });

  if (res.error) {
    const e = res.error as NodeJS.ErrnoException;
    if (e.code === 'ENOENT') {
      throw new Error(`'${cmd.bin}' was not found on your PATH.`);
    }
    throw res.error;
  }
  if (res.status !== 0) {
    throw new Error(`'${cmd.bin}' exited with code ${res.status}:\n${res.stderr}`);
  }
  return (res.stdout || '').trim();
}

function resolveAgent(preferred?: Agent): Agent {
  if (preferred) return preferred;
  const has = (bin: string) => spawnSync(bin, ['--version'], { encoding: 'utf8' }).status === 0;
  if (has('claude')) return 'claude';
  if (has('codex')) return 'codex';
  throw new Error('Neither `claude` nor `codex` was found on your PATH.');
}

export function digest(opts: DigestOptions = {}): string {
  const day = opts.day || localDay();
  const rows = promptsForDay(day);
  if (rows.length === 0) {
    throw new Error(`No prompts recorded for ${day}. Nothing to digest.`);
  }

  const agent = resolveAgent(opts.agent);
  const outPath = resolve(opts.out || 'digest.md');

  console.log(`rudder: ${rows.length} prompts on ${day}; summarizing with ${agent}...`);

  const instruction = buildInstruction(day, renderPrompts(rows));
  const body = runAgent(agent, instruction);

  const header = `# Work Digest — ${day}\n\n> Generated by rudder from ${rows.length} prompts across Claude Code & Codex.\n\n`;
  writeFileSync(outPath, header + body + '\n');
  console.log(`rudder: wrote ${outPath}`);
  return outPath;
}
